markdown: kramdown
url: ''
baseurl: null
title: Behold The Monkey
description: we are Behold The Monkey
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: /widershot.jpg
email: something@beholdthemonkey.com
facebook_username: Behold-The-Monkey
twitter_username: null
instagram_username: behold.the.monkey
linkedin_username: null
github_username: null
youtube_channel_id: null
reddit_username: null
behance_username: null
dribbble_username: null
spotify_username: null
google-analytics: null
disqus-shortname: null
author-name: Behold The Monkey
author-image: '/close.jpg'
author-about: >-
  We are a Stonner Rock band from Nantes, 
  et nous sommes la pour casser des culs.
author-url: 'beholdthemonkey.com'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
