markdown: kramdown
url: ''
baseurl: null
title: Behold The Monkey
description: we are Behold The Monkey
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: http://localhost:4000/IMG-5480.jpg
email: something@beholdthemonkey.com
facebook_username: beholdthemonkey
twitter_username: /
instagram_username: behold.the.monkey
linkedin_username: /
github_username: /
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: /
disqus-shortname: /
author-name: /
author-image: 'http://localhost:4000/IMG-5480.jpg'
author-about: >-
  We are a Stonner Rock band from Nantes, 
  et nous sommes la pour casser des culs.
author-url: 'https://github.com/KevinAllegretti'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
